#!/bin/bash

if [ "$#" != 4 ]
then
  echo "Syntax:  $0  <commonrev> <newbranch>  <oldfile> <newfile>" >&2
  exit 1
fi

set -x

COMMONREV="$1"
NEWREV="$2"
OLDFILE="$3"
NEWFILE="$4"


git merge-associate $NEWFILE $COMMONREV:$OLDFILE $NEWREV:$NEWFILE
git mergetool $NEWFILE
