#!/bin/bash

USERHOST=${!#}
HOST=${!#/*@/}
if [ -z "$HOST" ]; then
  echo Error: hostname not specified >&2
  exit 1
fi
mkdir -p /Volumes/$HOST
sshfs $USERHOST:/ -ofollow_symlinks /Volumes/$HOST
ssh "$@"
umount /Volumes/$HOST
