#!/bin/bash

userhost=${!#}
host=${!#/*@/}
if [ -z "$host" ]; then
  echo Error: hostname not specified >&2
  exit 1
fi
mkdir -p /Volumes/$host
sshfs $userhost:/ -ofollow_symlinks /Volumes/$host
ssh "$@"
umount /Volumes/$host
